Vagrant.configure(2) do |config|
  #Define two virtual machines, ubuntu1 and ubuntu2
  config.vm.define "ubuntu1" do |ubuntu1|
    #Select the image that we want
    ubuntu1.vm.box = "ubuntu/trusty64"
    #Setup a private network that allows both machines comms.
    ubuntu1.vm.network "private_network", ip:"10.0.0.10"
    ubuntu1.vm.hostname = "ubuntu1"
    ubuntu1.vm.provision "shell", inline: <<-SHELL
      echo "Local Configuration"
      if [ ! -f /vagrant/shared/ubuntu1 ]; then
        ssh-keygen -t rsa -P "" -f /vagrant/shared/ubuntu1
      fi
      cp /vagrant/shared/ubuntu1 /home/vagrant/.ssh/id_rsa
      chown vagrant /home/vagrant/.ssh/id_rsa
      chmod 600 /home/vagrant/.ssh/id_rsa
      cp /vagrant/shared/ubuntu1.pub /home/vagrant/.ssh/id_rsa.pub
      cat /vagrant/shared/ubuntu1.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "ubuntu/trusty64"
    ubuntu2.vm.network "private_network", ip:"10.0.0.11"
    ubuntu2.vm.hostname = "ubuntu2"
    ubuntu2.vm.provision "shell", inline: <<-SHELL
      echo "Local Configuration"
      cp /vagrant/shared/ubuntu1 /home/vagrant/.ssh/id_rsa
      chown vagrant /home/vagrant/.ssh/id_rsa
      chmod 600 /home/vagrant/.ssh/id_rsa
      cp /vagrant/shared/ubuntu1.pub /home/vagrant/.ssh/id_rsa.pub
      cat /vagrant/shared/ubuntu1.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
    #vb.memory = 2048
    #vb.memory = 3072
    #vb.memory = 4096
    vb.memory = 6192
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    #Update machine
    sudo apt-get update

    #Install outdated software
    sudo apt-get -y upgrade

    #Disable IPV6
    sudo echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
    sudo echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
    sudo echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf

    sudo sysctl -p

    #Configure hostname resolution
    sudo echo "127.0.0.1 localhost" > /etc/hosts
    sudo echo "10.0.0.10 ubuntu1.tallerhadoop1.org ubuntu1" >> /etc/hosts
    sudo echo "10.0.0.11 ubuntu2.tallerhadoop1.org ubuntu2" >> /etc/hosts

  SHELL
end
